version: '3'
services:
  frontend:
    container_name: frontend-react
    build: ./client
    volumes:
      - ./client/dist:/var/www/html
    ports:
      - 5050:80

  node:
    container_name: node_express_knex
    build: ./server
    volumes:
      - ./server:/app
    tty: true
    ports:
      - 6100:8080
    working_dir: /app
    environment:
      POSTGRES_HOST: '${DOCKER_POSTGTES_HOST}'
      POSTGRES_DB: '${DOCKER_POSTGRES_DB}'
      POSTGRES_USER: '${DOCKER_POSTGRES_USER}'
      POSTGRES_PASSWORD: '${DOCKER_POSTGRES_PASSWORD}'
      NODE_ENV: development
    command: >
      bash -c 'npm i && npm run build && npm run dev'
    depends_on:
      - postgres #必ず先にpostgresコンテナを立ち上げる

  postgres:
    container_name: '${DOCKER_POSTGTES_HOST}' #jsで指定するホストはこの名前にすること！！！
    image: postgres:14
    ports:
      - 6101:5432 # Out側(:の左)はホストマシンからのアクセスポートだが、実質使うことがないのでなんでも良い。内部側(:の右)はPostgresデフォルトの5432にして、JSからのアクセスポートもこの5432を使用することになる
    environment:
      POSTGRES_USER: '${DOCKER_POSTGRES_USER}'
      POSTGRES_PASSWORD: '${DOCKER_POSTGRES_PASSWORD}'
      POSTGRES_DB: '${DOCKER_POSTGRES_DB}' #ここで定義したデータベースが初期設定の際に作成される
    volumes:
      - ./server/postgres_db:/var/lib/postgresql/data
      # - ./initdb:/docker-entrypoint-initdb.d
